version: "3"

tasks:
  build:
    desc: Build the CLI tool
    cmds:
      - go build -o bin/loadtester ./cmd/loadtester

  run:
    desc: Run the CLI tool
    deps: [build]
    cmds:
      - ./bin/loadtester

  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

